version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mariadb