version: '3'

services:

    app:
        image: node:latest
        container_name: app
        ports:
            - 8080:80
        volumes:
            - ./app/:/app
        command:
            sh -c 'cd app && npm i && node index.js'
        
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        ports:
            - 3000:3000
    
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        restart: always
        ports:
            - 8086:8086
        environment:
            - INFLUXDB_DB=telegraf
            - INFLUXDB_USER=telegraf
            - INFLUXDB_ADMIN_ENABLED=true
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin 