version: '3'

services:

    balancer:
        image: nginx:latest
        container_name: balancer
        ports:
            - '8080:80'
        volumes:
            - ./config/balancer.conf:/etc/nginx/nginx.conf
        depends_on:
            - app1
            - app2

    app1:
        image: 'node:latest'
        container_name: app1
        volumes:
            - ./app/:/app
        ports:
            - 3000:3000
        environment:
            - NODE_ENV=development
            - PORT=3000
            - APP_NAME=App1
            - REDIS_URI=redis://redis:6379
        command:
            sh -c 'cd app && npm i && node index.js'
    
    app2:
        image: 'node:latest'
        container_name: app2
        volumes:
            - ./app/:/app
        ports:
            - 3001:3001
        environment:
            - NODE_ENV=development
            - PORT=3001
            - APP_NAME=App2
            - REDIS_URI=redis://redis:6379
        command:
            sh -c 'cd app && npm i && node index.js'
    
    redis:
         image: 'redis:latest'
         container_name: redis
         ports:
             - 6379:6379 
