version: '3'

services:
    app:
        image: 'node:latest'
        container_name: app
        volumes:
            - ./:/app
        ports:
            - 3000:3000
        environment:
            - NODE_ENV=development
            - PORT=3000
            - REDIS_URI=redis://redis:6379
        command:
            sh -c 'cd app && npm i && node index.js'
    
    redis:
        image: 'redis:latest'
        container_name: redis
        ports:
            - 6379:6379